"""
AI Quality Test: Interview Question Relevance

Purpose:
    Verify that the AI interviewer asks questions that are
    relevant to the candidate's role, experience, and the
    current interview topic.

Evaluation model:
    NVIDIA Nemotron (OpenAI-compatible API)
"""

from deepeval import assert_test
from config.settings import NVIDIA_BASE_URL, NVIDIA_MODEL
from evaluators.nvidia_judge import get_nvidia_judge
from deepeval.test_case import (
    LLMTestCase,
    SingleTurnParams,
)
from deepeval.metrics import GEval


# ============================================================
# Configuration
# ============================================================


QUESTION_RELEVANCE_THRESHOLD = 0.70


# ============================================================
# Evaluation model
# ============================================================

def create_evaluation_model():
    """
    Create the NVIDIA Nemotron judge used as the
    DeepEval evaluation judge.
    """

    return get_nvidia_judge()


# ============================================================
# Test data
# ============================================================

def create_question_relevance_test_case():
    """
    Create a realistic frontend developer interview scenario.

    INPUT:
        The interview context and candidate profile.

    ACTUAL_OUTPUT:
        The question generated by the AI interviewer.
    """

    interview_context = """
    Interview role:
    Frontend Developer

    Candidate background:
    The candidate has experience with React and JavaScript
    and has worked on a student management application.

    Current interview topic:
    React application development.

    The interviewer should ask a question that evaluates
    the candidate's frontend and React knowledge.
    """

    interviewer_question = (
        "You mentioned working with React in your student "
        "management application. How did you manage component "
        "state, and how did you decide which data should be "
        "stored locally versus shared between components?"
    )

    return LLMTestCase(
        input=interview_context,
        actual_output=interviewer_question,
    )


# ============================================================
# Evaluation metric
# ============================================================

def create_question_relevance_metric(model):
    """
    Create a GEval metric that evaluates whether the
    interviewer's question is relevant to the interview.
    """

    return GEval(
        name="Interview Question Relevance",

        criteria=(
            "Evaluate whether the interviewer's question is "
            "relevant to the interview role, the candidate's "
            "background, and the current interview topic. "
            "The question should be appropriate for a Frontend "
            "Developer interview and should meaningfully assess "
            "skills related to React, JavaScript, frontend "
            "development, or the candidate's stated experience."
        ),

        evaluation_params=[
            SingleTurnParams.INPUT,
            SingleTurnParams.ACTUAL_OUTPUT,
        ],

        evaluation_steps=[
            (
                "Identify the interview role and the expected "
                "technical domain from the input."
            ),
            (
                "Identify the candidate's relevant experience "
                "and background."
            ),
            (
                "Identify the topic addressed by the "
                "interviewer's question."
            ),
            (
                "Determine whether the question is relevant "
                "to the Frontend Developer role."
            ),
            (
                "Determine whether the question is relevant "
                "to the candidate's stated experience."
            ),
            (
                "Determine whether the question meaningfully "
                "assesses frontend or React knowledge."
            ),
            (
                "Penalize questions that are unrelated, random, "
                "too generic, or outside the interview context."
            ),
            (
                "Give a final score based on role relevance, "
                "candidate relevance, topic relevance, and "
                "technical usefulness."
            ),
        ],

        model=model,
        threshold=QUESTION_RELEVANCE_THRESHOLD,
    )


# ============================================================
# Test
# ============================================================

def test_question_relevance():
    """
    Verify that the AI interviewer asks a relevant
    interview question.
    """

    print()
    print("=" * 70)
    print("AI QUESTION RELEVANCE TEST")
    print("=" * 70)

    print()
    print(
        f"Evaluation model: {NVIDIA_MODEL}"
    )

    print(
        f"NVIDIA base URL: {NVIDIA_BASE_URL}"
    )

    print(
        f"Quality threshold: "
        f"{QUESTION_RELEVANCE_THRESHOLD}"
    )

    # --------------------------------------------------------
    # 1. Create evaluation model
    # --------------------------------------------------------

    print()
    print("Creating evaluation model...")

    model = create_evaluation_model()

    print(
        "[PASS] NVIDIA Nemotron evaluation model configured."
    )

    # --------------------------------------------------------
    # 2. Create test case
    # --------------------------------------------------------

    print()
    print("Creating interview test case...")

    test_case = (
        create_question_relevance_test_case()
    )

    print(
        "[PASS] Interview test case created."
    )

    # --------------------------------------------------------
    # 3. Create metric
    # --------------------------------------------------------

    print()
    print("Creating question relevance metric...")

    metric = create_question_relevance_metric(
        model
    )

    print(
        "[PASS] Question relevance metric configured."
    )

    # --------------------------------------------------------
    # 4. Run evaluation
    # --------------------------------------------------------

    print()
    print(
        "Evaluating interview question relevance..."
    )

    assert_test(
        test_case,
        [metric],
    )

    # --------------------------------------------------------
    # 5. Completed
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("QUESTION RELEVANCE TEST PASSED")
    print("=" * 70)
    