"""
Full Interview AI Quality Test

Purpose:
    Evaluate the overall quality of a complete AI interview
    using NVIDIA Nemotron via the OpenAI-compatible API.

Evaluates:
    - Context retention
    - Follow-up quality
    - Question relevance
    - Question repetition
    - Technical accuracy
    - Professionalism
    - Adaptability
    - Interview completeness
    - Overall interview quality
"""

import pytest

from deepeval import assert_test
from config.settings import NVIDIA_BASE_URL, NVIDIA_MODEL
from evaluators.nvidia_judge import get_nvidia_judge
from deepeval.metrics import GEval
from deepeval.test_case import (
    LLMTestCase,
    SingleTurnParams,
)


# ============================================================
# Configuration
# ============================================================


QUALITY_THRESHOLD = 0.70


# ============================================================
# Interview transcript
# ============================================================

def create_interview_transcript():
    """
    Return a representative complete frontend interview.

    IMPORTANT:
    Replace this transcript with the actual transcript
    generated by your EMH interview when transcript
    integration is available.
    """

    return """
INTERVIEWER:
Tell me about yourself and your experience with frontend development.

CANDIDATE:
I have experience with JavaScript and React. I built a
student management application using React where I worked
on reusable components, forms, tables and REST API integration.

INTERVIEWER:
Tell me more about your student management application.
What features did you personally implement?

CANDIDATE:
I implemented student listing, adding and editing students,
forms, tables and API integration. I also worked on the UI
and handled loading and error states.

INTERVIEWER:
How did you structure your React components?

CANDIDATE:
I created reusable components and passed data using props.
For local state I used useState.

INTERVIEWER:
When would you lift state up instead of keeping it inside
a component?

CANDIDATE:
If multiple components need the same state, I would move
the state to their common parent and pass the required
data and handlers through props.

INTERVIEWER:
What would you do if the application started rendering
the same component unnecessarily?

CANDIDATE:
I would investigate the component using React Developer
Tools and check whether props or state were changing
unnecessarily. I would optimize only after identifying
the actual cause.

INTERVIEWER:
How did you integrate the REST API?

CANDIDATE:
I used fetch to communicate with the backend and handled
loading, success and error states.

INTERVIEWER:
Suppose the API returns the correct data but the UI still
shows old information. How would you debug that?

CANDIDATE:
First I would inspect the network response. Then I would
check whether the response was stored correctly in state
and whether the component was actually using the updated
state.

INTERVIEWER:
What is a closure in JavaScript?

CANDIDATE:
A closure happens when a function retains access to variables
from its outer scope even after the outer function has finished.

INTERVIEWER:
Can you give me a practical use case for closures?

CANDIDATE:
They can be used to maintain private state or create functions
that remember values from their surrounding scope.

INTERVIEWER:
Your application has thousands of student records and the
page becomes slow. What would you investigate?

CANDIDATE:
I would inspect rendering performance, expensive operations
and the amount of data being loaded. I could use pagination
or virtualization if a large dataset is being displayed.

INTERVIEWER:
Would you immediately use useMemo and useCallback?

CANDIDATE:
No. I would first identify the actual performance problem.
Memoization should be used when it provides a real benefit.

INTERVIEWER:
How do you debug a JavaScript problem that you cannot
immediately understand?

CANDIDATE:
I reproduce the problem, inspect the console and network
requests, add breakpoints and isolate the code causing the
problem.

INTERVIEWER:
Tell me about a difficult problem you faced while building
your project.

CANDIDATE:
One issue was performance when displaying a large amount
of student data. I investigated unnecessary rendering and
optimized the way the data was displayed.

INTERVIEWER:
How would you make your UI responsive?

CANDIDATE:
I would use responsive CSS, Flexbox, Grid and media queries
and test the application at different screen sizes.

INTERVIEWER:
When would you choose CSS Grid instead of Flexbox?

CANDIDATE:
Grid is useful for two-dimensional layouts while Flexbox
is generally better for one-dimensional layouts.

INTERVIEWER:
How do you handle disagreements with another developer?

CANDIDATE:
I would discuss the different approaches, compare the
tradeoffs and choose the approach that is easier to maintain
and better fits the project requirements.

INTERVIEWER:
What would you improve in your student management application
if you had more time?

CANDIDATE:
I would improve separation between API logic and UI components,
make error handling more consistent and improve performance
for large datasets.

INTERVIEWER:
Thank you. Your interview is complete.
"""

# ============================================================
# Evaluation model
# ============================================================

@pytest.fixture(scope="module")
def evaluation_model():
    """
    Create one NVIDIA Nemotron evaluation model for the test module.
    """

    return get_nvidia_judge()


# ============================================================
# Full interview quality metric
# ============================================================

def create_full_interview_metric(model):
    """
    Create the GEval metric used to judge the complete
    interview.
    """

    return GEval(
        name="Full Interview Quality",

        criteria="""
Evaluate the overall quality of an AI technical interview.

The interviewer should:

1. Ask questions relevant to the candidate's role and experience.
2. Remember information from previous answers.
3. Ask meaningful follow-up questions.
4. Adapt questions based on the candidate's responses.
5. Avoid unnecessary repetition.
6. Ask technically accurate questions.
7. Maintain a professional and respectful tone.
8. Explore technical concepts beyond simple definitions.
9. Test practical debugging and problem-solving ability.
10. Cover an appropriate range of topics for the role.
11. Progress naturally from introductory questions to deeper
    technical questions.
12. Gather enough information to reasonably evaluate the candidate.
13. End the interview naturally after sufficient evaluation.

The final score should represent the quality of the interview
as a whole, not just the quality of individual questions.
""",

        evaluation_steps=[
            (
                "Identify the candidate's role, experience and "
                "technical background."
            ),

            (
                "Determine whether the interview questions are "
                "relevant to that background and the target role."
            ),

            (
                "Check whether the interviewer remembers and "
                "uses information from earlier answers."
            ),

            (
                "Check whether follow-up questions meaningfully "
                "explore previous candidate responses."
            ),

            (
                "Determine whether the interviewer adapts the "
                "interview based on candidate responses."
            ),

            (
                "Check whether questions are unnecessarily repeated."
            ),

            (
                "Evaluate the technical accuracy of the interview."
            ),

            (
                "Evaluate whether the interviewer maintains a "
                "professional and appropriate tone."
            ),

            (
                "Evaluate the depth of technical questioning."
            ),

            (
                "Evaluate whether practical debugging and "
                "problem-solving skills are tested."
            ),

            (
                "Evaluate the breadth of relevant interview topics."
            ),

            (
                "Evaluate whether the interview progresses naturally."
            ),

            (
                "Determine whether the interview gathers enough "
                "information to evaluate the candidate."
            ),

            (
                "Evaluate whether the interview concludes naturally "
                "after sufficient assessment."
            ),
        ],

        evaluation_params=[
            SingleTurnParams.INPUT,
            SingleTurnParams.ACTUAL_OUTPUT,
        ],

        model=model,
        threshold=QUALITY_THRESHOLD,
    )


# ============================================================
# Test
# ============================================================

def test_full_interview_quality(evaluation_model):
    """
    Evaluate the complete interview.
    """

    print()
    print("=" * 70)
    print("FULL INTERVIEW AI QUALITY TEST")
    print("=" * 70)

    print()
    print(f"Evaluation model: {NVIDIA_MODEL}")
    print(f"NVIDIA base URL: {NVIDIA_BASE_URL}")
    print(f"Quality threshold: {QUALITY_THRESHOLD}")

    # --------------------------------------------------------
    # Create transcript
    # --------------------------------------------------------

    print()
    print("Creating interview transcript...")

    transcript = create_interview_transcript()

    print("[PASS] Interview transcript created.")

    # --------------------------------------------------------
    # Create test case
    # --------------------------------------------------------

    print()
    print("Creating DeepEval test case...")

    test_case = LLMTestCase(
        input=transcript,
        actual_output=transcript,
    )

    print("[PASS] DeepEval test case created.")

    # --------------------------------------------------------
    # Create metric
    # --------------------------------------------------------

    print()
    print("Creating full interview quality metric...")

    metric = create_full_interview_metric(
        evaluation_model
    )

    print("[PASS] Full interview quality metric configured.")

    # --------------------------------------------------------
    # Evaluate
    # --------------------------------------------------------

    print()
    print("Evaluating complete interview...")
    print()

    assert_test(
        test_case,
        [metric],
    )

    # --------------------------------------------------------
    # Success
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("FULL INTERVIEW AI QUALITY TEST PASSED")
    print("=" * 70)