import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://hiring.easemyhiring.ai/jobs/1438/pipeline/")
    page.goto("https://hiring.easemyhiring.ai/")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("shivanshshuktel@volumetree.com")
    page.get_by_role("textbox", name="Email").press("Enter")
    page.locator("input[name=\"password\"]").press("CapsLock")
    page.locator("input[name=\"password\"]").fill("Volumetree")
    page.get_by_role("button", name="Show password").click()
    page.locator("input[name=\"password\"]").click()
    page.locator("input[name=\"password\"]").fill("Volumetree@123")
    page.locator("input[name=\"password\"]").press("Enter")
    page.locator(".absolute.inset-0.bg-\\[radial-gradient\\(ellipse_at_bottom_left\\,hsl\\(211_100\\%_50\\%\\/0\\.08\\)\\,transparent_60\\%\\)\\]").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("shivansh@volumetree.com")
    page.get_by_role("button", name="Hide password").click()
    page.get_by_role("button", name="Login").click()
    page.get_by_role("link", name="Jobs").click()
    page.get_by_role("option", name="Newest").click()
    page.get_by_role("combobox").filter(has_text="Sort: Newest").click()
    page.get_by_role("option", name="All").dblclick()
    page.get_by_role("combobox").filter(has_text="Position: All").click()
    page.locator("div").filter(has_text="All (1,085)All1,").nth(5).click()
    page.get_by_role("combobox").filter(has_text="Company: All").click()
    page.get_by_role("combobox").filter(has_text="Company: All").click()
    page.get_by_role("button", name="New job").click()
    page.get_by_role("link", name="Interviews").click()
    page.get_by_role("link", name="Jobs").click()
    page.get_by_role("button", name="Senior Backend Engineer").first.click()
    page.get_by_role("button", name="Pipeline").click()
    page.get_by_role("button", name="List").click()
    page.locator("tr:nth-child(41) > td:nth-child(3) > .rounded-md").select_option("outreach")
    page.get_by_role("cell", name="Outreach").first.click()
    page.locator("tr:nth-child(41) > td:nth-child(3) > .rounded-md").select_option("sourced")
    page.get_by_role("button", name="Kanban").click()
    page.get_by_role("button", name="Ingestion history").click()
    page.get_by_role("button", name="Add candidates").click()
    page.get_by_role("button", name="Upload Files").click()
    page.locator("form div").filter(has_text="Add Candidates").click()
    page.locator("form div").filter(has_text="Add Candidates").click()
    page.locator(".ag-center-cols-viewport").click()
    page.get_by_role("button", name="Upload Resumes max").click()
    page.locator("#upload-input").set_input_files(["06_Meera_Iyer_Resume.pdf", "08_Ananya_Sen_Resume.pdf", "09_Aditya_Verma_Resume.pdf", "10_Sana_Kapoor_Resume.pdf"])
    page.get_by_role("button", name="Add Candidates").click()
    page.get_by_role("button", name="Pipeline").click()
    page.get_by_text("GGauravdewli").click()
    page.get_by_role("button", name="Close").click()
    page.get_by_text("Ananya Sen").first.click()
    page.get_by_role("dialog").click()
    page.get_by_text("Kolkata, India").first.click()
    page.get_by_role("button", name="Show more").nth(1).click()
    page.get_by_role("dialog").click()
    page.get_by_text("How the 68/100 was calculated").click()
    page.get_by_role("button", name="View candidate").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)